//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiriusSyncr.App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiriusSyncr.App.AppKeys", typeof(AppKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1617273885202811.
        /// </summary>
        internal static string FacebookAppId {
            get {
                return ResourceManager.GetString("FacebookAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8aafbd1b9b444dc44321278666ab512c.
        /// </summary>
        internal static string FacebookAppSecret {
            get {
                return ResourceManager.GetString("FacebookAppSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 333607988004-a6qq30919ne0urs6jsm01jd6hp13gagu.apps.googleusercontent.com.
        /// </summary>
        internal static string GoogleClientId {
            get {
                return ResourceManager.GetString("GoogleClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T4xn5RyB-W2WwZc2gGK1dUUz.
        /// </summary>
        internal static string GoogleClientSecret {
            get {
                return ResourceManager.GetString("GoogleClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000000004C167661.
        /// </summary>
        internal static string MicrosoftClientId {
            get {
                return ResourceManager.GetString("MicrosoftClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YdjFmNxrbGpDYauVqJ7VCBkvh32gzNEe.
        /// </summary>
        internal static string MicrosoftClientSecret {
            get {
                return ResourceManager.GetString("MicrosoftClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TKubqJJrYdiJHr3nDq1WT99g9.
        /// </summary>
        internal static string TwitterConsumerKey {
            get {
                return ResourceManager.GetString("TwitterConsumerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hW8btgOllupDnBwWfdzkCUiGUjFM8qsuEGkx6nnSshwhHlbVBC.
        /// </summary>
        internal static string TwitterConsumerSecret {
            get {
                return ResourceManager.GetString("TwitterConsumerSecret", resourceCulture);
            }
        }
    }
}
